@startuml
class Form1 <<partial>> {
- globalCount : int = 0
+ Form1()
- deleteChildbox() : void
- addCatagory() : void
- catClick(sender:object, e:EventArgs) : void
- addItem(Price:decimal, Name:string, rowHeight:int) : void
- EnableSwipeToDelete(row:rowOfItem) : void
- updateTotalItems(number:int) : void
- updateTotalPrice(change:decimal) : void
- createScrollPanel() : void
- InitFoodList() : void
- deleteAllItemsOrdered() : void
- generalItem_Click(sender:object, e:EventArgs) : void
- backBtn_Click(sender:object, e:EventArgs) : void
- Form1_Load(sender:object, e:EventArgs) : void
- InitItemList(e:int) : void
- addLabel(tag:item) : void
- allPannelsBlank() : void
- ConfigBtn_Click(sender:object, e:EventArgs) : void
- FinalBtn_Click(sender:object, e:EventArgs) : void
- tableBottomBtn_Click(sender:object, e:EventArgs) : void
- OrderBtn_Click(sender:object, e:EventArgs) : void
- miscBtn_Click(sender:object, e:EventArgs) : void
- SignOnBtnConfigPanel_Click(sender:object, e:EventArgs) : void
- tableBtn_Click(sender:object, e:EventArgs) : void
- nameBtn_Click(sender:object, e:EventArgs) : void
- PricingBtn_Click(sender:object, e:EventArgs) : void
- CancelBtn_Click(sender:object, e:EventArgs) : void
}
class "List`1"<T> {
}
Form <|-- Form1
Form1 --> "currentStaff" staff
Form1 o-> "cat<catagory>" "List`1"
@enduml
