@startuml
!include .\\foodloader.puml
!include .\\Form1.puml
!include .\\Form1.Designer.puml
!include .\\NameForm.puml
!include .\\NameForm.Designer.puml
!include .\\Program.puml
!include .\\sqlSection.puml
!include .\\static classes.puml
!include .\\sync.puml
!include .\\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows\WorkCloneCS.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\WorkCloneCS.GlobalUsings.g.puml
!include .\\obj\x86\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\x86\Debug\net8.0-windows\WorkCloneCS.AssemblyInfo.puml
!include .\\obj\x86\Debug\net8.0-windows\WorkCloneCS.GlobalUsings.g.puml
@enduml
