@startuml
class NameForm <<partial>> {
- currentID : int = 0
+ NameForm()
- getStaff(filePath:string) : List<staff>
+ returnUserID() : int
- updateDisplayBtnText() : void
- numberBtn_Click(sender:object, e:EventArgs) : void
- btnEsc_Click(sender:object, e:EventArgs) : void
- btnOK_Click(sender:object, e:EventArgs) : void
}
class "List`1"<T> {
}
Form <|-- NameForm
NameForm --> "x<staff>" "List`1"
NameForm --> "staffSelected" staff
@enduml
