@startuml
class NameForm <<partial>> {
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
}
NameForm --> "panel1" Panel
NameForm --> "OKBtn" Button
NameForm --> "Btn0" Button
NameForm --> "EscBtn" Button
NameForm --> "Btn3" Button
NameForm --> "Btn2" Button
NameForm --> "Btn1" Button
NameForm --> "Btn6" Button
NameForm --> "Btn5" Button
NameForm --> "Btn4" Button
NameForm --> "Btn9" Button
NameForm --> "Btn8" Button
NameForm --> "Btn7" Button
NameForm --> "displayBtn" Button
@enduml
